package com.shuzutech.config;

public enum InterfaceNum {

    TEST, DEV, PRO, DEV1, DEV8 ,TEST1,
    PRINTDEV, PRINTPRO, PRINTQDDEV, PRINTQDPRO, PRINTTEST,PRINTQDTEST,
    BAIWANGTONGTEST,BAIWANGTONGDEV,BAIWANGTONGPRO

}
